name: Build ShoppyLine Web Application

on:
  push:
    branches: ['main']

jobs:
  build-project:
    name: Install Packages
    runs-on: ubuntu-latest
    defaults: 
      working-dirctory: ./Project/FE
    steps:
    # git clone current Repository to Cloud Computing Folder
    - name: Clone Main to Github CI/CD Folder
      uses: actions/checkout@v3
    - name: Echo CD 1
      run: |
        ls .
        ls .
    # - name: Install Packages
    #   run: npm install
    # - name: Building Project
    #   run: npm run build
    # - name: Echo
    #   run: ls
    