name: Build ShoppyLine Web Application

on:
  push:
    branches: ['main']

jobs:
  build-project:
    name: Front End Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project/FE
    steps:
      # git clone current Repository to Cloud Computing Folder
      - name: Clone Main to Github CI/CD Folder
        uses: actions/checkout@v3
      - name: Install Packages
        run: |
          npm install
          npm install -g firebase-tools
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: firebase deploy --token 1//0gEzrSKpg2Q3CCgYIARAAGBASNwF-L9IrsOD76hT9MtVFH8afTxnFfB59A06AlcPE4d2pgGX4XbwN9awGb5oai0cwzbQBhm6zMl8
