name: Build ShoppyLine Web Application

on:
  push:
    branches: ['main']

jobs:
  build-project:
    name: Install Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project/FE
    steps:
      # git clone current Repository to Cloud Computing Folder
      - name: Clone Main to Github CI/CD Folder
        uses: actions/checkout@v3
      - name: Install Packages
        run: |
          npm install
          npm install firebase
      - name: Build Project
        run: |
          npm run build
      - name: Echo Folder Project
        run: ls .
