name: Build ShoppyLine Web Application

on:
  push:
    branches: ['main']

jobs:
  build-project:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: CD Project
      run: cd Project/
    - name: Echo CD 1
      run: ls
    - name: CD FE
      run: cd FE/
    - name: Echo CD 2
      run: ls
    # - name: Install Packages
    #   run: npm install
    # - name: Building Project
    #   run: npm run build
    # - name: Echo
    #   run: ls
    