name: Build ShoppyLine Web Application

on:
  push:
    branches: ['main']

jobs:
  build-project:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Packages
      run: cd Project/FE && npm install
    - name: Building Project
      run: npm run build
    - name: Echo
      run: ls
    